window.GameData = {

    version:"1.1.0",

    fragmentValue:{ NORMAL:1, RARE:2, EPIC:3, LEGEND:5, SECRET:8 },
    fragmentCost:{ NORMAL:400, RARE:900, EPIC:1600, LEGEND:30000, SECRET:60000 },
    fragmentBoostMultiplier:3000,
    fragmentSkipCost:150,

    quotesByChapter:{
        "CH-000":[
            "오늘도 우리 이서를 만날 준비를 하고 있어요.",
            "작은 심장 소리가 두 사람의 하루를 채워요.",
            "매일 조금씩, 이서는 자라고 있어요.",
            "사진 한 장마다 그날의 마음이 담겨 있어요.",
            "함께 기다리는 시간도 소중한 이야기예요.",
            "오늘 하루도 이서 덕분에 웃었어요.",
            "느리지만 분명하게, 우리는 세 사람이 되어가요.",
            "이서가 건네는 작은 신호들을 기록해요.",
            "언젠가 이 사진첩을 함께 넘겨볼 날을 그려봐요.",
            "기다림도 사랑의 한 모습이에요.",
            "오늘의 태동, 오늘의 마음을 남겨두어요.",
            "작은 발걸음이 큰 이야기가 되고 있어요.",
            "두 사람에서 세 사람으로, 그 시작을 기록해요.",
            "매 순간이 이서에게 닿기를 바라요.",
            "오늘도 무사히, 함께여서 다행이에요."
        ],
        "CH-001":[
            "드디어 우리 이서를 만났어요.",
            "작은 숨소리 하나에도 마음이 벅차요.",
            "처음 안아본 순간을 잊지 못할 거예요.",
            "밤새 뒤척여도 이서 얼굴을 보면 힘이 나요.",
            "매일 조금씩 자라는 모습이 신기해요.",
            "우리는 이제 셋이에요.",
            "작은 손을 잡고 오늘 하루도 감사해요.",
            "이서의 첫 순간들을 하나씩 기록해요.",
            "울음소리마저 사랑스러운 요즘이에요.",
            "함께한 첫날들을 오래 기억하고 싶어요."
        ],
        "CH-002":[
            "어느새 백일이 훌쩍 지나갔어요.",
            "하루가 다르게 웃음이 늘어가요.",
            "뒤집기 성공, 오늘도 한 뼘 자랐어요.",
            "옹알이 소리가 하루 종일 귓가에 맴돌아요.",
            "백일의 기적을 함께 축하해요.",
            "이서와 함께한 100일, 감사한 나날이에요.",
            "작은 몸짓 하나에도 온 가족이 웃어요.",
            "매일 새로운 모습을 보여주는 이서예요.",
            "백일 사진 속 미소가 오래오래 남았으면 해요.",
            "함께 자라는 시간이 참 소중해요."
        ]
    },

    // 사진 파일 번호는 챕터당 100개씩 예약해서 사용해요 (향후 확장 대비).
    // CH-000 Prologue   → card0001~0100 (현재 1~50 사용)
    // CH-001 Welcome Baby → card0101~0200 (현재 101~150 사용)
    // CH-002 100일        → card0201~0300 (현재 201~250 사용)
    // 새 챕터를 추가할 때는 다음 100번대(예: card0301~)를 사용하면 돼요.
    chapters:[
        {
            id:"CH-000",
            title:"Prologue",
            description:"새로운 생명의 시작",
            cards:["MEM-0001","MEM-0002","MEM-0003","MEM-0004","MEM-0005","MEM-0006","MEM-0007","MEM-0008","MEM-0009","MEM-0010","MEM-0011","MEM-0012","MEM-0013","MEM-0014","MEM-0015","MEM-0016","MEM-0017","MEM-0018","MEM-0019","MEM-0020","MEM-0021","MEM-0022","MEM-0023","MEM-0024","MEM-0025","MEM-0026","MEM-0027","MEM-0028","MEM-0029","MEM-0030","MEM-0031","MEM-0032","MEM-0033","MEM-0034","MEM-0035","MEM-0036","MEM-0037","MEM-0038","MEM-0039","MEM-0040","MEM-0041","MEM-0042","MEM-0043","MEM-0044","MEM-0045","MEM-0046","MEM-0047","MEM-0048","MEM-0049","MEM-0050"]
        },
        {
            id:"CH-001",
            title:"Welcome Baby",
            description:"우리 아가와의 첫 만남",
            cards:["WB-0001","WB-0002","WB-0003","WB-0004","WB-0005","WB-0006","WB-0007","WB-0008","WB-0009","WB-0010","WB-0011","WB-0012","WB-0013","WB-0014","WB-0015","WB-0016","WB-0017","WB-0018","WB-0019","WB-0020","WB-0021","WB-0022","WB-0023","WB-0024","WB-0025","WB-0026","WB-0027","WB-0028","WB-0029","WB-0030","WB-0031","WB-0032","WB-0033","WB-0034","WB-0035","WB-0036","WB-0037","WB-0038","WB-0039","WB-0040","WB-0041","WB-0042","WB-0043","WB-0044","WB-0045","WB-0046","WB-0047","WB-0048","WB-0049","WB-0050"]
        },
        {
            id:"CH-002",
            title:"100일",
            description:"백일의 기적, 자라나는 하루하루",
            cards:["D100-0001","D100-0002","D100-0003","D100-0004","D100-0005","D100-0006","D100-0007","D100-0008","D100-0009","D100-0010","D100-0011","D100-0012","D100-0013","D100-0014","D100-0015","D100-0016","D100-0017","D100-0018","D100-0019","D100-0020","D100-0021","D100-0022","D100-0023","D100-0024","D100-0025","D100-0026","D100-0027","D100-0028","D100-0029","D100-0030","D100-0031","D100-0032","D100-0033","D100-0034","D100-0035","D100-0036","D100-0037","D100-0038","D100-0039","D100-0040","D100-0041","D100-0042","D100-0043","D100-0044","D100-0045","D100-0046","D100-0047","D100-0048","D100-0049","D100-0050"]
        }
    ],

    cards:[
        {
            id:"MEM-0001",
            chapterId:"CH-000",
            order:1,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"새로운 생명의 시작",
            date:"2025-04-29",
            description:"두 사람이 아닌 세 사람의 이야기가 시작된 순간",
            photo:"card0001.png",
            requires:[],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0002",
            chapterId:"CH-000",
            order:2,
            rarity:"RARE",
            drawWeight:30,
            type:"FIRST",
            title:"두 줄의 기적",
            date:"2025-06-02",
            description:"기다리고 기다리던 새로운 생명의 시작을 처음 확인한 특별한 순간",
            photo:"card0002.png",
            requires:["MEM-0001"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0003",
            chapterId:"CH-000",
            order:3,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"달라진 하루의 시작",
            date:"2025-06-03",
            description:"평범했던 하루가 새로운 의미를 갖기 시작한 순간",
            photo:"card0003.png",
            requires:["MEM-0002"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0004",
            chapterId:"CH-000",
            order:4,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"첫 병원 방문",
            date:"2025-06-05",
            description:"작은 생명을 확인하기 위해 처음 병원을 찾은 소중한 날",
            photo:"card0004.png",
            requires:["MEM-0002"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0005",
            chapterId:"CH-000",
            order:5,
            rarity:"RARE",
            drawWeight:30,
            type:"CHECKUP",
            title:"우리 가족이 된 첫 순간",
            date:"2025-06-21",
            description:"처음으로 화면 속 작은 생명의 모습을 확인한 특별한 기록",
            photo:"card0005.png",
            requires:["MEM-0004"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0006",
            chapterId:"CH-000",
            order:6,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"작은 생명의 모습",
            date:"2025-06-21",
            description:"초음파 화면 속에서 조금씩 자라고 있는 아기의 모습을 만난 날",
            photo:"card0006.png",
            requires:["MEM-0005"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0007",
            chapterId:"CH-000",
            order:7,
            rarity:"LEGEND",
            drawWeight:3,
            type:"FIRST",
            title:"처음 들은 심장 소리",
            date:"2025-06-21",
            description:"작지만 분명하게 들려온 생명의 신호를 처음 만난 순간",
            photo:"card0007.png",
            requires:["MEM-0006"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0008",
            chapterId:"CH-000",
            order:8,
            rarity:"RARE",
            drawWeight:30,
            type:"ULTRASOUND",
            title:"첫 초음파 사진",
            date:"2025-06-21",
            description:"우리 아기의 첫 모습을 사진으로 남긴 소중한 기억",
            photo:"card0008.png",
            requires:["MEM-0007"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0009",
            chapterId:"CH-000",
            order:9,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"손과 발을 확인하다",
            date:"2025-07-19",
            description:"작은 손과 발이 자라고 있음을 확인하며 한 걸음 더 가까워진 날",
            photo:"card0009.png",
            requires:["MEM-0008"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0010",
            chapterId:"CH-000",
            order:10,
            rarity:"LEGEND",
            drawWeight:3,
            type:"ULTRASOUND",
            title:"입체초음파 첫 만남",
            date:"2025-11-08",
            description:"평면 화면을 넘어 아기의 모습을 조금 더 선명하게 만난 특별한 순간",
            photo:"card0010.png",
            requires:["MEM-0009"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0011",
            chapterId:"CH-000",
            order:11,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"산전 기형아 검사",
            date:"2025-08-20",
            description:"아기의 건강한 성장을 확인하기 위해 중요한 검사를 진행한 날",
            photo:"card0011.png",
            requires:["MEM-0010"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0012",
            chapterId:"CH-000",
            order:12,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"두 번째 성장 확인",
            date:"2025-08-16",
            description:"조금씩 자라나는 아기의 모습을 다시 만난 소중한 초음파 기록",
            photo:"card0012.png",
            requires:["MEM-0011"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0013",
            chapterId:"CH-000",
            order:13,
            rarity:"RARE",
            drawWeight:30,
            type:"FIRST",
            title:"처음 느낀 태동",
            date:"2025-08-25",
            description:"엄마와 아기가 처음으로 서로의 존재를 느낀 특별한 순간",
            photo:"card0013.png",
            requires:["MEM-0012"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0014",
            chapterId:"CH-000",
            order:14,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"성별 확인",
            date:"2025-08-25",
            description:"오랫동안 기다려온 아기의 이야기를 조금 더 알게 된 날",
            photo:"card0014.png",
            requires:["MEM-0013"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0015",
            chapterId:"CH-000",
            order:15,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"배가 조금씩 커지는 시간",
            date:"2025-09-20",
            description:"아기가 자라는 만큼 엄마의 하루도 조금씩 변화하기 시작한 시간",
            photo:"card0015.png",
            requires:["MEM-0014"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0016",
            chapterId:"CH-000",
            order:16,
            rarity:"RARE",
            drawWeight:30,
            type:"PHOTO",
            title:"아기와 함께한 첫 사진",
            date:"2025-10-05",
            description:"엄마와 아기가 함께 남긴 특별한 가족의 기록",
            photo:"card0016.png",
            requires:["MEM-0015"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0017",
            chapterId:"CH-000",
            order:17,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"정밀 초음파 검사",
            date:"2025-10-11",
            description:"아기의 성장 모습을 자세히 확인하며 건강을 확인한 날",
            photo:"card0017.png",
            requires:["MEM-0016"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0018",
            chapterId:"CH-000",
            order:18,
            rarity:"RARE",
            drawWeight:30,
            type:"FAMILY",
            title:"가족에게 전한 소식",
            date:"2025-10-15",
            description:"새로운 가족을 기다리는 마음을 함께 나눈 따뜻한 순간",
            photo:"card0018.png",
            requires:["MEM-0017"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0019",
            chapterId:"CH-000",
            order:19,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"아기 이름 고민하기",
            date:"2025-11-01",
            description:"우리 아기에게 어울리는 이름을 고민하기 시작한 시간",
            photo:"card0019.png",
            requires:["MEM-0018"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0020",
            chapterId:"CH-000",
            order:20,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"임당 검사",
            date:"2025-11-10",
            description:"엄마와 아기의 건강을 위해 꼼꼼하게 확인한 중요한 검사",
            photo:"card0020.png",
            requires:["MEM-0019"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0021",
            chapterId:"CH-000",
            order:21,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"아기 용품 준비 시작",
            date:"2025-11-25",
            description:"아기를 만날 준비를 시작하며 작은 설렘을 채워간 시간",
            photo:"card0021.png",
            requires:["MEM-0020"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0022",
            chapterId:"CH-000",
            order:22,
            rarity:"EPIC",
            drawWeight:10,
            type:"PHOTO",
            title:"만삭 사진 촬영",
            date:"2025-12-05",
            description:"아기를 기다리는 지금의 모습을 오래 기억하기 위해 남긴 특별한 기록",
            photo:"card0022.png",
            requires:["MEM-0021"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:30,
            skillValueWeight:1
        },
        {
            id:"MEM-0023",
            chapterId:"CH-000",
            order:23,
            rarity:"RARE",
            drawWeight:30,
            type:"ULTRASOUND",
            title:"출산 전 마지막 초음파",
            date:"2026-01-23",
            description:"곧 만나게 될 아기의 모습을 마지막으로 확인한 소중한 순간",
            photo:"card0023.png",
            requires:["MEM-0022"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0024",
            chapterId:"CH-000",
            order:24,
            rarity:"EPIC",
            drawWeight:10,
            type:"MILESTONE",
            title:"출산 준비 완료",
            date:"2026-02-01",
            description:"아기를 맞이하기 위한 모든 준비를 마친 설레는 순간",
            photo:"card0024.png",
            requires:["MEM-0023"],
            maxLevel:30,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0025",
            chapterId:"CH-000",
            order:25,
            rarity:"LEGEND",
            drawWeight:1,
            type:"SPECIAL",
            title:"마지막 기다림",
            date:"2026-02-02",
            description:"새로운 가족을 만나기 바로 전날, 가장 설레는 기다림의 순간",
            photo:"card0025.png",
            requires:["MEM-0024"],
            maxLevel:40,
            skill:"UNLOCK_POINTS",
            skillValue:1,
            skillValueWeight:0
        },
        {
            id:"MEM-0026",
            chapterId:"CH-000",
            order:26,
            rarity:"RARE",
            drawWeight:30,
            type:"PREPARATION",
            title:"국민행복카드",
            date:"2025-06-18",
            description:"임신을 확인하고 발급받은 국민행복카드 엄마로서 첫 행정 절차",
            photo:"card0026.png",
            requires:["MEM-0002"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0027",
            chapterId:"CH-000",
            order:27,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"처음 찾아간 보건소",
            date:"2025-06-26",
            description:"엄마와 아기를 위한 지원을 알아보고 준비를 시작한 날",
            photo:"card0027.png",
            requires:["MEM-0004"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0028",
            chapterId:"CH-000",
            order:28,
            rarity:"NORMAL",
            drawWeight:100,
            type:"PREPARATION",
            title:"아기를 위한 작은 준비",
            date:"2025-06-26",
            description:"건강한 만남을 위해 매일 이어갈 준비를 시작한 순간",
            photo:"card0028.png",
            requires:["MEM-0027"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0029",
            chapterId:"CH-000",
            order:29,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"작은 행복이 된 간식",
            date:"2025-07-03",
            description:"임신 중 만난 평범하지만 오래 기억될 작은 순간",
            photo:"card0029.png",
            requires:["MEM-0028"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0030",
            chapterId:"CH-000",
            order:30,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마를 위한 건강 습관",
            date:"2025-07-12",
            description:"아기를 생각하는 마음으로 하루를 채워간 시간",
            photo:"card0030.png",
            requires:["MEM-0029"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0031",
            chapterId:"CH-000",
            order:31,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"태아보험",
            date:"2025-07-18",
            description:"아기의 미래를 생각하며 처음 준비한 보호의 기록",
            photo:"card0031.png",
            requires:["MEM-0007","MEM-0026"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0032",
            chapterId:"CH-000",
            order:32,
            rarity:"RARE",
            drawWeight:30,
            type:"SHOPPING",
            title:"아기 선물",
            date:"2025-07-20",
            description:"삼촌이 사준 아주 작은 옷과 양말",
            photo:"card0032.png",
            requires:["MEM-0007","MEM-0031"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0033",
            chapterId:"CH-000",
            order:33,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"임산부 배지",
            date:"2025-07-25",
            description:"임산부 배지를 달고 처음 외출하며 엄마로서의 정체성을 실감한 순간",
            photo:"card0033.png",
            requires:["MEM-0032"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0034",
            chapterId:"CH-000",
            order:34,
            rarity:"NORMAL",
            drawWeight:100,
            type:"PREPARATION",
            title:"매일 이어지는 사랑",
            date:"2025-08-02",
            description:"아기의 건강을 위해 꾸준히 준비한 시간",
            photo:"card0034.png",
            requires:["MEM-0033"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0035",
            chapterId:"CH-000",
            order:35,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"다가오는 만남을 위한 준비",
            date:"2025-08-08",
            description:"앞으로 남을 특별한 순간을 준비하기 시작한 날",
            photo:"card0035.png",
            requires:["MEM-0010","MEM-0034"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0036",
            chapterId:"CH-000",
            order:36,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"아무도 모르는 작은 기록",
            date:"2025-06-26",
            description:"사진으로 남기지 못했지만 마음속에 남아있는 특별한 순간",
            photo:"card0036.png",
            requires:["MEM-0002","MEM-0027","MEM-0028","MEM-0031"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        },
        {
            id:"MEM-0037",
            chapterId:"CH-000",
            order:37,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"준비",
            date:"2025-07-20",
            description:"아기를 기다리는 마음으로 준비한 작은 선물",
            photo:"card0037.png",
            requires:["MEM-0007","MEM-0031","MEM-0032"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0038",
            chapterId:"CH-000",
            order:38,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"우리 가족의 공간",
            date:"2025-08-21",
            description:"아기를 맞이할 준비를 하며 새로운 공간을 만들어가기 시작한 날",
            photo:"card0038.png",
            requires:["MEM-0035","MEM-0034"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0039",
            chapterId:"CH-000",
            order:39,
            rarity:"RARE",
            drawWeight:30,
            type:"BODY_CHANGE",
            title:"엄마에게 남은 작은 흔적",
            date:"2025-08-31",
            description:"아기가 자라고 있다는 것을 느끼게 해준 특별한 변화",
            photo:"card0039.png",
            requires:["MEM-0013","MEM-0034"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0040",
            chapterId:"CH-000",
            order:40,
            rarity:"EPIC",
            drawWeight:10,
            type:"MILESTONE",
            title:"두 사람이 세 사람이 되는 의미",
            date:"2025-08-31",
            description:"가족이라는 의미를 다시 생각하게 된 특별한 하루",
            photo:"card0040.png",
            requires:["MEM-0001","MEM-0031"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0041",
            chapterId:"CH-000",
            order:41,
            rarity:"LEGEND",
            drawWeight:3,
            type:"TRAVEL",
            title:"마지막 둘만의 여행",
            date:"2025-09-04",
            description:"아기를 만나기 전 두 사람이 함께 남긴 마지막 특별한 여행",
            photo:"card0041.png",
            requires:["MEM-0013","MEM-0038","MEM-0040"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:30,
            skillValueWeight:1
        },
        {
            id:"MEM-0042",
            chapterId:"CH-000",
            order:42,
            rarity:"RARE",
            drawWeight:30,
            type:"FAMILY",
            title:"함께 기다리는 가족",
            date:"2025-09-13",
            description:"새로운 가족을 기다리는 마음을 함께 나눈 따뜻한 시간",
            photo:"card0042.png",
            requires:["MEM-0041"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0043",
            chapterId:"CH-000",
            order:43,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"아기를 위한 첫 번째 공간",
            date:"2025-09-17",
            description:"작은 물건 하나하나에 사랑을 담아 준비하기 시작한 날",
            photo:"card0043.png",
            requires:["MEM-0038","MEM-0032"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0044",
            chapterId:"CH-000",
            order:44,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마를 위한 작은 휴식",
            date:"2025-10-01",
            description:"아기를 기다리는 엄마를 위해 준비한 작은 선물",
            photo:"card0044.png",
            requires:["MEM-0038"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0045",
            chapterId:"CH-000",
            order:45,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"D - 100",
            date:"2025-10-25",
            description:"아기를 기다린 시간도 하나의 추억이 된 특별한 날",
            photo:"card0045.png",
            requires:["MEM-0001","MEM-0041"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0046",
            chapterId:"CH-000",
            order:46,
            rarity:"RARE",
            drawWeight:30,
            type:"MEMORY",
            title:"초음파앨범",
            date:"2025-10-27",
            description:"소중한 순간들을 모아 하나의 이야기로 만들 준비를 시작한 날",
            photo:"card0046.png",
            requires:["MEM-0022","MEM-0045"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0047",
            chapterId:"CH-000",
            order:47,
            rarity:"RARE",
            drawWeight:30,
            type:"TRAVEL",
            title:"화담숲",
            date:"2025-11-01",
            description:"아기를 기다리며 남긴 따뜻한 계절의 기록",
            photo:"card0047.png",
            requires:["MEM-0041"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0048",
            chapterId:"CH-000",
            order:48,
            rarity:"EPIC",
            drawWeight:10,
            type:"PHOTO",
            title:"만삭사진",
            date:"2025-11-05",
            description:"만남을 앞두고 특별한 기록을 남기기 위해 준비한 시간",
            photo:"card0048.png",
            requires:["MEM-0022","MEM-0046"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0049",
            chapterId:"CH-000",
            order:49,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"세 사람의 이름",
            date:"2025-12-02",
            description:"가족이 될 순간을 기다리며 준비한 작은 장식",
            photo:"card0049.png",
            requires:["MEM-0048"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0050",
            chapterId:"CH-000",
            order:50,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"겨울의 작은 행복",
            date:"2025-12-23",
            description:"특별한 사건은 아니지만 오래 기억될 평범하고 따뜻한 하루",
            photo:"card0050.png",
            requires:["MEM-0045","MEM-0047","MEM-0049"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        },
        {
            id:"WB-0001",
            chapterId:"CH-001",
            order:1,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"출생",
            date:"2025-12-27",
            description:"세상에 처음 나온 그 순간, 모든 것이 시작됐어요",
            photo:"card0101.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0002",
            chapterId:"CH-001",
            order:2,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"출생신고",
            date:"2025-12-27",
            description:"작은 이름 하나가 세상에 정식으로 새겨진 날",
            photo:"card0102.png",
            requires:[],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0003",
            chapterId:"CH-001",
            order:3,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"신생아실",
            date:"2025-12-28",
            description:"유리창 너머로 처음 얼굴을 마주한 순간",
            photo:"card0103.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0004",
            chapterId:"CH-001",
            order:4,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"병원 팔찌",
            date:"2025-12-28",
            description:"작은 손목에 채워진, 세상에서 가장 소중한 이름표",
            photo:"card0104.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0005",
            chapterId:"CH-001",
            order:5,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마 품",
            date:"2025-12-29",
            description:"세상에서 가장 편안한 자리, 엄마 품에 안긴 순간",
            photo:"card0105.png",
            requires:[],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0006",
            chapterId:"CH-001",
            order:6,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"아빠 품",
            date:"2025-12-29",
            description:"든든한 두 팔 안에서 새근새근 잠든 시간",
            photo:"card0106.png",
            requires:["WB-0001"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0007",
            chapterId:"CH-001",
            order:7,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 수유",
            date:"2025-12-30",
            description:"처음으로 배부르게 먹은, 작지만 큰 성취",
            photo:"card0107.png",
            requires:["WB-0001"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0008",
            chapterId:"CH-001",
            order:8,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 분유",
            date:"2025-12-30",
            description:"낯선 맛에 오물거리던 작은 입",
            photo:"card0108.png",
            requires:["WB-0001"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0009",
            chapterId:"CH-001",
            order:9,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 하품",
            date:"2025-12-30",
            description:"세상에서 가장 귀여운 하품 한 번",
            photo:"card0109.png",
            requires:["WB-0001"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0010",
            chapterId:"CH-001",
            order:10,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 재채기",
            date:"2025-12-31",
            description:"에취, 놀랍도록 우렁찼던 작은 재채기",
            photo:"card0110.png",
            requires:["WB-0001"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0011",
            chapterId:"CH-001",
            order:11,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 미소",
            date:"2025-12-31",
            description:"우연이었을까요, 그래도 세상이 환해졌던 미소",
            photo:"card0111.png",
            requires:["WB-0006"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0012",
            chapterId:"CH-001",
            order:12,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"작은 손",
            date:"2026-01-01",
            description:"손가락 하나하나까지 완벽했던 작은 손",
            photo:"card0112.png",
            requires:["WB-0006"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0013",
            chapterId:"CH-001",
            order:13,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"작은 발",
            date:"2026-01-01",
            description:"이불 밖으로 삐죽 나온 작은 발가락",
            photo:"card0113.png",
            requires:["WB-0006"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0014",
            chapterId:"CH-001",
            order:14,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"퇴원",
            date:"2026-01-02",
            description:"드디어 셋이 함께 집으로 향하는 날",
            photo:"card0114.png",
            requires:["WB-0006"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0015",
            chapterId:"CH-001",
            order:15,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"카시트",
            date:"2026-01-02",
            description:"어색하지만 안전하게, 첫 자동차 여행",
            photo:"card0115.png",
            requires:["WB-0006"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0016",
            chapterId:"CH-001",
            order:16,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"집으로",
            date:"2026-01-02",
            description:"기다리던 우리 집, 이제 셋이 되어 돌아왔어요",
            photo:"card0116.png",
            requires:["WB-0011"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0017",
            chapterId:"CH-001",
            order:17,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"조리원",
            date:"2026-01-03",
            description:"몸을 추스르며 육아를 배워가던 시간",
            photo:"card0117.png",
            requires:["WB-0011"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0018",
            chapterId:"CH-001",
            order:18,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"이름표",
            date:"2026-01-03",
            description:"작은 이름이 적힌, 세상에서 가장 소중한 표식",
            photo:"card0118.png",
            requires:["WB-0011"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0019",
            chapterId:"CH-001",
            order:19,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 목욕",
            date:"2026-01-04",
            description:"물이 낯설어 앙앙 울던 첫 목욕 시간",
            photo:"card0119.png",
            requires:["WB-0011"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0020",
            chapterId:"CH-001",
            order:20,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 손톱",
            date:"2026-01-04",
            description:"너무 작아서 조심스러웠던 첫 손톱 정리",
            photo:"card0120.png",
            requires:["WB-0011"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0021",
            chapterId:"CH-001",
            order:21,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"기저귀",
            date:"2026-01-05",
            description:"하루에도 몇 번씩, 서툴지만 정성스럽던 손길",
            photo:"card0121.png",
            requires:["WB-0016"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0022",
            chapterId:"CH-001",
            order:22,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"쪽쪽이",
            date:"2026-01-05",
            description:"쪽쪽이 하나로 세상 편안해지던 표정",
            photo:"card0122.png",
            requires:["WB-0016"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0023",
            chapterId:"CH-001",
            order:23,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"포대기",
            date:"2026-01-05",
            description:"꽁꽁 싸매어 안았던 포근한 순간",
            photo:"card0123.png",
            requires:["WB-0016"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0024",
            chapterId:"CH-001",
            order:24,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 잠",
            date:"2026-01-06",
            description:"처음으로 새근새근 잠든 얼굴을 오래 바라봤어요",
            photo:"card0124.png",
            requires:["WB-0016"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0025",
            chapterId:"CH-001",
            order:25,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"새벽 수유",
            date:"2026-01-06",
            description:"모두가 잠든 새벽, 우리 둘만 깨어 있던 시간",
            photo:"card0125.png",
            requires:["WB-0016"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0026",
            chapterId:"CH-001",
            order:26,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"울음",
            date:"2026-01-07",
            description:"우렁찬 울음소리마저 사랑스러웠던 순간",
            photo:"card0126.png",
            requires:["WB-0021"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0027",
            chapterId:"CH-001",
            order:27,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"트림",
            date:"2026-01-07",
            description:"토닥토닥, 시원하게 트림하던 순간",
            photo:"card0127.png",
            requires:["WB-0021"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0028",
            chapterId:"CH-001",
            order:28,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"체온계",
            date:"2026-01-08",
            description:"조금만 열이 나도 마음 졸이던 순간",
            photo:"card0128.png",
            requires:["WB-0021"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0029",
            chapterId:"CH-001",
            order:29,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"체중측정",
            date:"2026-01-08",
            description:"하루가 다르게 늘어가던 몸무게",
            photo:"card0129.png",
            requires:["WB-0021"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0030",
            chapterId:"CH-001",
            order:30,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"병원 검사",
            date:"2026-01-08",
            description:"건강하게 자라는지 확인하러 간 날",
            photo:"card0130.png",
            requires:["WB-0021"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0031",
            chapterId:"CH-001",
            order:31,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 셀카",
            date:"2026-01-09",
            description:"휴대폰 카메라 속에 처음 담긴 작은 얼굴",
            photo:"card0131.png",
            requires:["WB-0026"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0032",
            chapterId:"CH-001",
            order:32,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"가족사진",
            date:"2026-01-09",
            description:"셋이 함께, 처음으로 남긴 가족의 기록",
            photo:"card0132.png",
            requires:["WB-0026"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0033",
            chapterId:"CH-001",
            order:33,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"햇살",
            date:"2026-01-10",
            description:"창가에 스며든 따뜻한 햇살 아래 잠든 얼굴",
            photo:"card0133.png",
            requires:["WB-0026"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0034",
            chapterId:"CH-001",
            order:34,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"손가락",
            date:"2026-01-10",
            description:"꼭 쥔 작은 손가락의 힘이 생각보다 셌어요",
            photo:"card0134.png",
            requires:["WB-0026"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0035",
            chapterId:"CH-001",
            order:35,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마 웃음",
            date:"2026-01-11",
            description:"아이를 바라보며 저절로 번진 엄마의 미소",
            photo:"card0135.png",
            requires:["WB-0026"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"WB-0036",
            chapterId:"CH-001",
            order:36,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"아빠 웃음",
            date:"2026-01-11",
            description:"서툴지만 행복이 가득했던 아빠의 미소",
            photo:"card0136.png",
            requires:["WB-0031"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"WB-0037",
            chapterId:"CH-001",
            order:37,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"축하꽃",
            date:"2026-01-11",
            description:"축하한다는 말과 함께 도착한 꽃다발",
            photo:"card0137.png",
            requires:["WB-0031"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0038",
            chapterId:"CH-001",
            order:38,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"선물",
            date:"2026-01-12",
            description:"작은 존재를 위해 하나둘 쌓여가던 선물들",
            photo:"card0138.png",
            requires:["WB-0031"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"WB-0039",
            chapterId:"CH-001",
            order:39,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"행복",
            date:"2026-01-12",
            description:"별일 아닌 하루에도 벅차게 차오르던 행복",
            photo:"card0139.png",
            requires:["WB-0031"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"WB-0040",
            chapterId:"CH-001",
            order:40,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"기억",
            date:"2026-01-13",
            description:"오래오래 남기고 싶어 마음에 새긴 순간",
            photo:"card0140.png",
            requires:["WB-0031"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0041",
            chapterId:"CH-001",
            order:41,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"추억",
            date:"2026-01-13",
            description:"시간이 지나도 잊지 못할 소중한 하루",
            photo:"card0141.png",
            requires:["WB-0036"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"WB-0042",
            chapterId:"CH-001",
            order:42,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"사랑",
            date:"2026-01-14",
            description:"말로 다 못할 만큼 커져만 가던 사랑",
            photo:"card0142.png",
            requires:["WB-0036"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"WB-0043",
            chapterId:"CH-001",
            order:43,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"성장",
            date:"2026-01-14",
            description:"어제와는 또 다른 모습으로 자라나던 하루",
            photo:"card0143.png",
            requires:["WB-0036"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0044",
            chapterId:"CH-001",
            order:44,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"Epic 하루",
            date:"2026-01-14",
            description:"돌아보면 더없이 소중했던 하루의 한 장면",
            photo:"card0144.png",
            requires:["WB-0036"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"WB-0045",
            chapterId:"CH-001",
            order:45,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"Epic 가족",
            date:"2026-01-15",
            description:"평범한 하루가 특별한 기억으로 남는 시간",
            photo:"card0145.png",
            requires:["WB-0036"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:12,
            skillValueWeight:1
        },
        {
            id:"WB-0046",
            chapterId:"CH-001",
            order:46,
            rarity:"EPIC",
            drawWeight:10,
            type:"FIRST",
            title:"첫 외출",
            date:"2026-01-15",
            description:"세상 구경을 나선 첫 나들이",
            photo:"card0146.png",
            requires:["WB-0041"],
            maxLevel:30,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0047",
            chapterId:"CH-001",
            order:47,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"귀가",
            date:"2026-01-16",
            description:"돌아보면 더없이 소중했던 하루의 한 장면",
            photo:"card0147.png",
            requires:["WB-0041"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"WB-0048",
            chapterId:"CH-001",
            order:48,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"가족의 시작",
            date:"2026-01-16",
            description:"둘에서 셋이 된, 우리 가족의 진짜 시작",
            photo:"card0148.png",
            requires:["WB-0041"],
            maxLevel:40,
            skill:"DRAW_COOLDOWN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"WB-0049",
            chapterId:"CH-001",
            order:49,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"우리",
            date:"2026-01-17",
            description:"이제는 '우리'라는 말이 더 크게 느껴지던 날",
            photo:"card0149.png",
            requires:["WB-0041"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"WB-0050",
            chapterId:"CH-001",
            order:50,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"새로운 인생",
            date:"2026-01-17",
            description:"작은 존재 하나로 완전히 달라진 우리의 인생",
            photo:"card0150.png",
            requires:["WB-0001","WB-0036","WB-0048","WB-0049"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        },
        {
            id:"D100-0001",
            chapterId:"CH-002",
            order:1,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"백일상",
            date:"2026-02-23",
            description:"백일을 축하하며 정성껏 차린 상",
            photo:"card0201.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0002",
            chapterId:"CH-002",
            order:2,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"백일사진",
            date:"2026-02-24",
            description:"백일을 기념해 남긴 특별한 사진",
            photo:"card0202.png",
            requires:[],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0003",
            chapterId:"CH-002",
            order:3,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 한복",
            date:"2026-02-25",
            description:"작은 몸에 맞춰 지은 예쁜 첫 한복",
            photo:"card0203.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0004",
            chapterId:"CH-002",
            order:4,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 웃음",
            date:"2026-02-26",
            description:"소리 내어 처음으로 까르르 웃던 순간",
            photo:"card0204.png",
            requires:[],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0005",
            chapterId:"CH-002",
            order:5,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"뒤집기",
            date:"2026-02-26",
            description:"낑낑대다 마침내 성공한 첫 뒤집기",
            photo:"card0205.png",
            requires:[],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0006",
            chapterId:"CH-002",
            order:6,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"배밀이",
            date:"2026-02-27",
            description:"팔다리를 바삐 움직이며 앞으로 나아가던 순간",
            photo:"card0206.png",
            requires:["D100-0001"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0007",
            chapterId:"CH-002",
            order:7,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"장난감",
            date:"2026-02-28",
            description:"손에 쥐고 놓지 않던 첫 장난감",
            photo:"card0207.png",
            requires:["D100-0001"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0008",
            chapterId:"CH-002",
            order:8,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"모빌",
            date:"2026-03-01",
            description:"천천히 도는 모빌을 넋 놓고 바라보던 눈",
            photo:"card0208.png",
            requires:["D100-0001"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0009",
            chapterId:"CH-002",
            order:9,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"딸랑이",
            date:"2026-03-02",
            description:"흔들 때마다 반짝이던 눈빛",
            photo:"card0209.png",
            requires:["D100-0001"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0010",
            chapterId:"CH-002",
            order:10,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 외출",
            date:"2026-03-03",
            description:"세상 구경을 나선 첫 나들이",
            photo:"card0210.png",
            requires:["D100-0001"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0011",
            chapterId:"CH-002",
            order:11,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"유모차",
            date:"2026-03-04",
            description:"유모차에 앉아 세상을 구경하던 시간",
            photo:"card0211.png",
            requires:["D100-0006"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0012",
            chapterId:"CH-002",
            order:12,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"공원",
            date:"2026-03-04",
            description:"바람을 느끼며 함께 걸었던 공원 산책",
            photo:"card0212.png",
            requires:["D100-0006"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0013",
            chapterId:"CH-002",
            order:13,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"햇살",
            date:"2026-03-05",
            description:"창가에 스며든 따뜻한 햇살 아래 잠든 얼굴",
            photo:"card0213.png",
            requires:["D100-0006"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0014",
            chapterId:"CH-002",
            order:14,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"낮잠",
            date:"2026-03-06",
            description:"세상 모르고 곤히 자던 낮잠 시간",
            photo:"card0214.png",
            requires:["D100-0006"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0015",
            chapterId:"CH-002",
            order:15,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"품속",
            date:"2026-03-07",
            description:"품에 안겨야만 편안해지던 작은 존재",
            photo:"card0215.png",
            requires:["D100-0006"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0016",
            chapterId:"CH-002",
            order:16,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"손가락",
            date:"2026-03-08",
            description:"꼭 쥔 작은 손가락의 힘이 생각보다 셌어요",
            photo:"card0216.png",
            requires:["D100-0011"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0017",
            chapterId:"CH-002",
            order:17,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 옹알이",
            date:"2026-03-09",
            description:"무슨 말인지 몰라도 사랑스러웠던 옹알이",
            photo:"card0217.png",
            requires:["D100-0011"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0018",
            chapterId:"CH-002",
            order:18,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마 바라보기",
            date:"2026-03-10",
            description:"눈을 맞추고 한참을 바라보던 순간",
            photo:"card0218.png",
            requires:["D100-0011"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0019",
            chapterId:"CH-002",
            order:19,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"아빠 바라보기",
            date:"2026-03-10",
            description:"아빠 얼굴을 신기하게 올려다보던 눈빛",
            photo:"card0219.png",
            requires:["D100-0011"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0020",
            chapterId:"CH-002",
            order:20,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 책",
            date:"2026-03-11",
            description:"처음으로 펼쳐본 알록달록한 그림책",
            photo:"card0220.png",
            requires:["D100-0011"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0021",
            chapterId:"CH-002",
            order:21,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"거울",
            date:"2026-03-12",
            description:"거울 속 자신을 신기하게 바라보던 순간",
            photo:"card0221.png",
            requires:["D100-0016"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0022",
            chapterId:"CH-002",
            order:22,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"손도장",
            date:"2026-03-13",
            description:"조그맣게 남긴 손도장 하나",
            photo:"card0222.png",
            requires:["D100-0016"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0023",
            chapterId:"CH-002",
            order:23,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"발도장",
            date:"2026-03-14",
            description:"꼭 눌러 남긴 작은 발도장",
            photo:"card0223.png",
            requires:["D100-0016"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0024",
            chapterId:"CH-002",
            order:24,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"우유",
            date:"2026-03-15",
            description:"쭉쭉 잘도 먹던 하루의 우유",
            photo:"card0224.png",
            requires:["D100-0016"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0025",
            chapterId:"CH-002",
            order:25,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"이유식 준비",
            date:"2026-03-16",
            description:"새로운 맛을 위해 정성껏 준비한 이유식",
            photo:"card0225.png",
            requires:["D100-0016"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0026",
            chapterId:"CH-002",
            order:26,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 친구",
            date:"2026-03-16",
            description:"처음으로 만난 또래 친구",
            photo:"card0226.png",
            requires:["D100-0021"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0027",
            chapterId:"CH-002",
            order:27,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 인형",
            date:"2026-03-17",
            description:"품에 꼭 안고 놓지 않던 첫 인형",
            photo:"card0227.png",
            requires:["D100-0021"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0028",
            chapterId:"CH-002",
            order:28,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 모자",
            date:"2026-03-18",
            description:"작은 머리에 씌운 첫 모자",
            photo:"card0228.png",
            requires:["D100-0021"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0029",
            chapterId:"CH-002",
            order:29,
            rarity:"NORMAL",
            drawWeight:100,
            type:"FIRST",
            title:"첫 신발",
            date:"2026-03-19",
            description:"아직 걷지도 못하는데 신겨본 첫 신발",
            photo:"card0229.png",
            requires:["D100-0021"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0030",
            chapterId:"CH-002",
            order:30,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"가족 모임",
            date:"2026-03-20",
            description:"온 가족이 모여 함께 축하한 날",
            photo:"card0230.png",
            requires:["D100-0021"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0031",
            chapterId:"CH-002",
            order:31,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"촛불",
            date:"2026-03-21",
            description:"작은 케이크 위, 함께 불어본 촛불",
            photo:"card0231.png",
            requires:["D100-0026"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0032",
            chapterId:"CH-002",
            order:32,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"축하",
            date:"2026-03-22",
            description:"모두의 축하가 쏟아지던 특별한 하루",
            photo:"card0232.png",
            requires:["D100-0026"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0033",
            chapterId:"CH-002",
            order:33,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"미소",
            date:"2026-03-22",
            description:"보기만 해도 마음이 놓이던 미소",
            photo:"card0233.png",
            requires:["D100-0026"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0034",
            chapterId:"CH-002",
            order:34,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"행복",
            date:"2026-03-23",
            description:"별일 아닌 하루에도 벅차게 차오르던 행복",
            photo:"card0234.png",
            requires:["D100-0026"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0035",
            chapterId:"CH-002",
            order:35,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"기념",
            date:"2026-03-24",
            description:"오래도록 간직하고 싶은 기념의 순간",
            photo:"card0235.png",
            requires:["D100-0026"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"D100-0036",
            chapterId:"CH-002",
            order:36,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"추억",
            date:"2026-03-25",
            description:"시간이 지나도 잊지 못할 소중한 하루",
            photo:"card0236.png",
            requires:["D100-0031"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"D100-0037",
            chapterId:"CH-002",
            order:37,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"성장",
            date:"2026-03-26",
            description:"어제와는 또 다른 모습으로 자라나던 하루",
            photo:"card0237.png",
            requires:["D100-0031"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0038",
            chapterId:"CH-002",
            order:38,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"사랑",
            date:"2026-03-27",
            description:"말로 다 못할 만큼 커져만 가던 사랑",
            photo:"card0238.png",
            requires:["D100-0031"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"D100-0039",
            chapterId:"CH-002",
            order:39,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"백일 케이크",
            date:"2026-03-28",
            description:"백일을 축하하며 준비한 달콤한 케이크",
            photo:"card0239.png",
            requires:["D100-0031"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"D100-0040",
            chapterId:"CH-002",
            order:40,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"웃음소리",
            date:"2026-03-28",
            description:"온 집안을 채우던 사랑스러운 웃음소리",
            photo:"card0240.png",
            requires:["D100-0031"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0041",
            chapterId:"CH-002",
            order:41,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"Epic 미소",
            date:"2026-03-29",
            description:"보기만 해도 마음이 놓이던 미소",
            photo:"card0241.png",
            requires:["D100-0036"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"D100-0042",
            chapterId:"CH-002",
            order:42,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"Epic 성장",
            date:"2026-03-30",
            description:"어제와는 또 다른 모습으로 자라나던 하루",
            photo:"card0242.png",
            requires:["D100-0036"],
            maxLevel:25,
            skill:"DRAW_COOLDOWN",
            skillValue:8,
            skillValueWeight:1
        },
        {
            id:"D100-0043",
            chapterId:"CH-002",
            order:43,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"Epic 시간",
            date:"2026-03-31",
            description:"돌아보면 더없이 소중했던 하루의 한 장면",
            photo:"card0243.png",
            requires:["D100-0036"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0044",
            chapterId:"CH-002",
            order:44,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"Epic 사랑",
            date:"2026-04-01",
            description:"말로 다 못할 만큼 커져만 가던 사랑",
            photo:"card0244.png",
            requires:["D100-0036"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"D100-0045",
            chapterId:"CH-002",
            order:45,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"축복",
            date:"2026-04-02",
            description:"주변의 축복 속에 자라나는 하루하루",
            photo:"card0245.png",
            requires:["D100-0036"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:12,
            skillValueWeight:1
        },
        {
            id:"D100-0046",
            chapterId:"CH-002",
            order:46,
            rarity:"EPIC",
            drawWeight:10,
            type:"SPECIAL",
            title:"백일의 기적",
            date:"2026-04-03",
            description:"백일이라는 시간이 만들어낸 작은 기적",
            photo:"card0246.png",
            requires:["D100-0041"],
            maxLevel:30,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0047",
            chapterId:"CH-002",
            order:47,
            rarity:"EPIC",
            drawWeight:10,
            type:"FIRST",
            title:"첫 계절",
            date:"2026-04-03",
            description:"태어나 처음 맞이한 계절의 변화",
            photo:"card0247.png",
            requires:["D100-0041"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"D100-0048",
            chapterId:"CH-002",
            order:48,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"Legend 백일",
            date:"2026-04-04",
            description:"작은 변화 하나에도 마음이 벅차오르던 순간",
            photo:"card0248.png",
            requires:["D100-0041"],
            maxLevel:40,
            skill:"DRAW_COOLDOWN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"D100-0049",
            chapterId:"CH-002",
            order:49,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"Secret 기적",
            date:"2026-04-05",
            description:"말로 다 표현할 수 없는 작은 순간들이 쌓여가요",
            photo:"card0249.png",
            requires:["D100-0041"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"D100-0050",
            chapterId:"CH-002",
            order:50,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"영원한 기억",
            date:"2026-04-06",
            description:"시간이 흘러도 영원히 남을 우리의 기억",
            photo:"card0250.png",
            requires:["D100-0001","D100-0036","D100-0048","D100-0049"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        }
    ]
};
