window.GameData = {
    version: "0.1.3",
    chapters: [
        {
            id: "CH-000",
            title: "Prologue",
            description: "새로운 생명의 시작",
            cards: ["MEM-0001","MEM-0002","MEM-0003","MEM-0004","MEM-0005",
					"MEM-0006","MEM-0007","MEM-0008","MEM-0009","MEM-0010",
					"MEM-0011","MEM-0012","MEM-0013","MEM-0014","MEM-0015",
					"MEM-0016","MEM-0017","MEM-0018","MEM-0019","MEM-0020",
					"MEM-0021","MEM-0022","MEM-0023","MEM-0024","MEM-0025",]
        },
        {
            id: "CH-001",
            title: "Before Birth",
            description: "엄마 뱃속에서의 시간",
            cards: ["MEM-0026","MEM-0027","MEM-0028"]
        }
    ],
    cards: [
        {
            id:"MEM-0001",
            chapterId:"CH-000",
            order:1,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"새로운 생명의 시작",
            week:"",
            date:"2025-06-01",
            description:"두 사람이 아닌 세 사람의 이야기가 시작된 순간",
            photo:"card0001.png",
            aiLog:"New life signature detected.",
            requires:[],
            maxLevel:10,
            skill:"DRAW_COUNT",
            skillValue:1
        },
        {
            id:"MEM-0002",
            chapterId:"CH-000",
            order:2,
            rarity:"RARE",
            drawWeight:30,
            type:"FIRST",
            title:"두 줄의 기적",
            week:"",
            date:"2025-06-03",
            description:"작은 변화가 찾아왔음을 처음 알게 된 순간",
            photo:"card0002.png",
            aiLog:"Pregnancy confirmation detected.",
            requires:["MEM-0001"],
            maxLevel:5,
            skill:"POINT_GAIN",
            skillValue:5
        },
        {
            id:"MEM-0003",
            chapterId:"CH-000",
            order:3,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"달라진 하루",
            week:"",
            date:"2025-06-05",
            description:"평범했던 일상이 특별하게 변하기 시작한 날",
            photo:"card0003.png",
            aiLog:"Emotional pattern changed.",
            requires:["MEM-0002"],
            maxLevel:3,
            skill:"DRAW_COOLDOWN",
            skillValue:5
        },
        {
            id:"MEM-0004",
            chapterId:"CH-000",
            order:4,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"첫 병원 방문",
            week:"5주차",
            date:"2025-06-10",
            description:"작은 생명을 만나기 위해 처음 병원을 찾은 날",
            photo:"card0004.png",
            aiLog:"Medical memory recovered.",
            requires:["MEM-0002"],
            maxLevel:7,
            skill:"POINT_GAIN",
            skillValue:10
        },
        {
            id:"MEM-0005",
            chapterId:"CH-000",
            order:5,
            rarity:"RARE",
            drawWeight:30,
            type:"CHECKUP",
            title:"임신 확인",
            week:"5주차",
            date:"2025-06-10",
            description:"우리 가족에게 새로운 시작이 확정된 순간",
            photo:"card0005.png",
            aiLog:"Life confirmation completed.",
            requires:["MEM-0004"],
            maxLevel:5,
            skill:"DRAW_COUNT",
            skillValue:1
        },
        {
            id:"MEM-0006",
            chapterId:"CH-000",
            order:6,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"작은 생명의 모습",
            week:"6주차",
            date:"2025-06-15",
            description:"처음으로 화면 속 작은 모습을 확인한 날",
            photo:"card0006.png",
            aiLog:"Visual memory recovered.",
            requires:["MEM-0005"],
            maxLevel:7,
            skill:"POINT_GAIN",
            skillValue:10
        },
        {
            id:"MEM-0007",
            chapterId:"CH-000",
            order:7,
            rarity:"LEGEND",
            drawWeight:3,
            type:"FIRST",
            title:"처음 들은 심장 소리",
            week:"7주차",
            date:"2025-06-20",
            description:"작지만 분명한 생명의 신호를 들은 순간",
            photo:"card0007.png",
            aiLog:"Heartbeat signature detected.",
            requires:["MEM-0006"],
            maxLevel:10,
            skill:"DRAW_COUNT",
            skillValue:2
        },
		{
			id:"MEM-0008",
			chapterId:"CH-000",
			order:8,
			rarity:"RARE",
			drawWeight:30,
			type:"PHOTO",
			title:"첫 초음파 사진",
			week:"7주차 5일",
			date:"2025-06-21",
			description:"우리 아기의 첫 모습을 사진으로 남긴 특별한 날",
			photo:"card0008.png",
			aiLog:"First visual memory stored.",
			requires:["MEM-0007"],
			maxLevel:5,
			skill:"POINT_GAIN",
			skillValue:10
		},
		{
			id:"MEM-0009",
			chapterId:"CH-000",
			order:9,
			rarity:"EPIC",
			drawWeight:10,
			type:"CHECKUP",
			title:"손과 발을 확인하다",
			week:"7주차 5일",
			date:"2025-06-21",
			description:"작은 손과 발이 자라고 있음을 확인한 순간",
			photo:"card0009.png",
			aiLog:"Limb development detected.",
			requires:["MEM-0008"],
			maxLevel:7,
			skill:"POINT_GAIN",
			skillValue:15
		},
		{
			id:"MEM-0010",
			chapterId:"CH-000",
			order:10,
			rarity:"LEGEND",
			drawWeight:3,
			type:"MILESTONE",
			title:"입체초음파 첫 만남",
			week:"12주차",
			date:"2025-07-20",
			description:"평면 화면을 넘어 처음으로 얼굴을 상상할 수 있었던 순간",
			photo:"card0010.png",
			aiLog:"Three dimensional image reconstructed.",
			requires:["MEM-0009"],
			maxLevel:10,
			skill:"DRAW_COUNT",
			skillValue:2
		},
		{
			id:"MEM-0011",
			chapterId:"CH-000",
			order:11,
			rarity:"EPIC",
			drawWeight:10,
			type:"CHECKUP",
			title:"니프티 검사",
			week:"12주차",
			date:"2025-07-25",
			description:"건강한 만남을 준비하기 위한 중요한 검사",
			photo:"card0011.png",
			aiLog:"Genetic analysis record found.",
			requires:["MEM-0010"],
			maxLevel:7,
			skill:"POINT_GAIN",
			skillValue:15
		},
		{
			id:"MEM-0012",
			chapterId:"CH-000",
			order:12,
			rarity:"EPIC",
			drawWeight:10,
			type:"CHECKUP",
			title:"목덜미 투명대 검사",
			week:"12주차",
			date:"2025-07-25",
			description:"아기가 건강하게 성장하고 있는지 확인한 날",
			photo:"card0012.png",
			aiLog:"Growth condition analyzed.",
			requires:["MEM-0011"],
			maxLevel:7,
			skill:"DRAW_COOLDOWN",
			skillValue:10
		},
		{
			id:"MEM-0013",
			chapterId:"CH-000",
			order:13,
			rarity:"RARE",
			drawWeight:30,
			type:"FIRST",
			title:"처음 느낀 태동",
			week:"16주차",
			date:"2025-08-25",
			description:"엄마와 아기가 처음으로 교감한 순간",
			photo:"card0013.png",
			aiLog:"Movement interaction detected.",
			requires:["MEM-0012"],
			maxLevel:5,
			skill:"POINT_GAIN",
			skillValue:20
		},
		{
			id:"MEM-0014",
			chapterId:"CH-000",
			order:14,
			rarity:"LEGEND",
			drawWeight:3,
			type:"MILESTONE",
			title:"성별 확인",
			week:"16주차",
			date:"2025-08-25",
			description:"오랫동안 기다려온 우리 아기의 모습을 더 가까이 알게 된 날",
			photo:"card0014.png",
			aiLog:"Identity information recovered.",
			requires:["MEM-0013"],
			maxLevel:10,
			skill:"DRAW_COUNT",
			skillValue:2
		},
		{
			id:"MEM-0015",
			chapterId:"CH-000",
			order:15,
			rarity:"NORMAL",
			drawWeight:100,
			type:"DAILY",
			title:"배가 조금씩 커지는 시간",
			week:"20주차",
			date:"2025-09-20",
			description:"아기가 자라는 만큼 엄마의 하루도 변화하기 시작했다",
			photo:"card0015.png",
			aiLog:"Growth progress recorded.",
			requires:["MEM-0014"],
			maxLevel:3,
			skill:"DRAW_COOLDOWN",
			skillValue:5
		},
		{
			id:"MEM-0016",
			chapterId:"CH-000",
			order:16,
			rarity:"RARE",
			drawWeight:30,
			type:"PHOTO",
			title:"배 속 아기와 함께한 사진",
			week:"22주차",
			date:"2025-10-05",
			description:"엄마와 아기가 함께 남긴 첫 번째 기록",
			photo:"card0016.png",
			aiLog:"Family photo memory detected.",
			requires:["MEM-0015"],
			maxLevel:5,
			skill:"POINT_GAIN",
			skillValue:20
		},
		{
			id:"MEM-0017",
			chapterId:"CH-000",
			order:17,
			rarity:"EPIC",
			drawWeight:10,
			type:"CHECKUP",
			title:"정밀 초음파 검사",
			week:"22주차",
			date:"2025-10-10",
			description:"아기의 성장 상태를 자세히 확인한 날",
			photo:"card0017.png",
			aiLog:"Detailed growth scan completed.",
			requires:["MEM-0016"],
			maxLevel:7,
			skill:"POINT_GAIN",
			skillValue:20
		},
		{
			id:"MEM-0018",
			chapterId:"CH-000",
			order:18,
			rarity:"RARE",
			drawWeight:30,
			type:"FAMILY",
			title:"가족에게 전한 소식",
			week:"23주차",
			date:"2025-10-15",
			description:"새로운 가족을 기다리는 마음을 함께 나눈 날",
			photo:"card0018.png",
			aiLog:"Social memory detected.",
			requires:["MEM-0017"],
			maxLevel:5,
			skill:"DRAW_COUNT",
			skillValue:1
		},
		{
			id:"MEM-0019",
			chapterId:"CH-000",
			order:19,
			rarity:"NORMAL",
			drawWeight:100,
			type:"DAILY",
			title:"아기 이름 고민하기",
			week:"25주차",
			date:"2025-11-01",
			description:"아기에게 어울리는 이름을 생각하기 시작한 시간",
			photo:"card0019.png",
			aiLog:"Naming memory discovered.",
			requires:["MEM-0018"],
			maxLevel:3,
			skill:"POINT_GAIN",
			skillValue:5
		},
		{
			id:"MEM-0020",
			chapterId:"CH-000",
			order:20,
			rarity:"EPIC",
			drawWeight:10,
			type:"CHECKUP",
			title:"임당 검사",
			week:"26주차",
			date:"2025-11-10",
			description:"엄마와 아기의 건강을 확인하는 중요한 검사",
			photo:"card0020.png",
			aiLog:"Health examination recorded.",
			requires:["MEM-0019"],
			maxLevel:7,
			skill:"DRAW_COOLDOWN",
			skillValue:10
		},
		{
			id:"MEM-0021",
			chapterId:"CH-000",
			order:21,
			rarity:"RARE",
			drawWeight:30,
			type:"SPECIAL",
			title:"아기 용품 준비 시작",
			week:"28주차",
			date:"2025-11-25",
			description:"만남을 준비하며 작은 물건들을 준비한 시간",
			photo:"card0021.png",
			aiLog:"Preparation memory detected.",
			requires:["MEM-0020"],
			maxLevel:5,
			skill:"DRAW_COUNT",
			skillValue:1
		},
		{
			id:"MEM-0022",
			chapterId:"CH-000",
			order:22,
			rarity:"EPIC",
			drawWeight:10,
			type:"PHOTO",
			title:"만삭 사진 촬영",
			week:"32주차",
			date:"2025-12-25",
			description:"출산 전 마지막으로 남긴 소중한 기록",
			photo:"card0022.png",
			aiLog:"Final pregnancy memory stored.",
			requires:["MEM-0021"],
			maxLevel:7,
			skill:"POINT_GAIN",
			skillValue:30
		},
		{
			id:"MEM-0023",
			chapterId:"CH-000",
			order:23,
			rarity:"RARE",
			drawWeight:30,
			type:"DAILY",
			title:"만남을 기다리는 하루",
			week:"36주차",
			date:"2026-01-20",
			description:"아기를 만날 날을 기다리는 설레는 시간",
			photo:"card0023.png",
			aiLog:"Anticipation emotion detected.",
			requires:["MEM-0022"],
			maxLevel:5,
			skill:"POINT_GAIN",
			skillValue:20
		},
		{
			id:"MEM-0024",
			chapterId:"CH-000",
			order:24,
			rarity:"EPIC",
			drawWeight:10,
			type:"MILESTONE",
			title:"출산 준비 완료",
			week:"38주차",
			date:"2026-02-01",
			description:"이제 아기를 만날 준비가 모두 끝난 순간",
			photo:"card0024.png",
			aiLog:"Birth preparation completed.",
			requires:["MEM-0023"],
			maxLevel:7,
			skill:"DRAW_COUNT",
			skillValue:2
		},
		{
			id:"MEM-0025",
			chapterId:"CH-000",
			order:25,
			rarity:"LEGEND",
			drawWeight:1,
			type:"SPECIAL",
			title:"마지막 기다림",
			week:"출산 직전",
			date:"2026-02-02",
			description:"새로운 가족을 만나기 바로 전날의 특별한 순간",
			photo:"card0025.png",
			aiLog:"Final countdown detected.",
			requires:["MEM-0024"],
			maxLevel:10,
			skill:"UNLOCK_CHAPTER",
			skillValue:1
		}
    ],
	
    endings:[]
};