window.GameData = {

    version:"1.0.4",

    chapters:[
        {
            id:"CH-000",
            title:"Prologue",
            description:"새로운 생명의 시작",
            cards:["MEM-0001","MEM-0002","MEM-0003","MEM-0004","MEM-0005","MEM-0006","MEM-0007","MEM-0008","MEM-0009","MEM-0010","MEM-0011","MEM-0012","MEM-0013","MEM-0014","MEM-0015","MEM-0016","MEM-0017","MEM-0018","MEM-0019","MEM-0020","MEM-0021","MEM-0022","MEM-0023","MEM-0024","MEM-0025","MEM-0026","MEM-0027","MEM-0028","MEM-0029","MEM-0030","MEM-0031","MEM-0032","MEM-0033","MEM-0034","MEM-0035","MEM-0036","MEM-0037","MEM-0038","MEM-0039","MEM-0040","MEM-0041","MEM-0042","MEM-0043","MEM-0044","MEM-0045","MEM-0046","MEM-0047","MEM-0048","MEM-0049","MEM-0050"]
        },
        {
            id:"CH-001",
            title:"Before Birth",
            description:"엄마 뱃속에서의 시간",
            cards:[]
        }
    ],

    cards:[
        {
            id:"MEM-0001",
            chapterId:"CH-000",
            order:1,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"새로운 생명의 시작",
            date:"2025-04-29",
            description:"두 사람이 아닌 세 사람의 이야기가 시작된 순간",
            photo:"card0001.png",
            requires:[],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0002",
            chapterId:"CH-000",
            order:2,
            rarity:"RARE",
            drawWeight:30,
            type:"FIRST",
            title:"두 줄의 기적",
            date:"2025-06-02",
            description:"기다리고 기다리던 새로운 생명의 시작을 처음 확인한 특별한 순간",
            photo:"card0002.png",
            requires:["MEM-0001"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0003",
            chapterId:"CH-000",
            order:3,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"달라진 하루의 시작",
            date:"2025-06-03",
            description:"평범했던 하루가 새로운 의미를 갖기 시작한 순간",
            photo:"card0003.png",
            requires:["MEM-0002"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0004",
            chapterId:"CH-000",
            order:4,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"첫 병원 방문",
            date:"2025-06-05",
            description:"작은 생명을 확인하기 위해 처음 병원을 찾은 소중한 날",
            photo:"card0004.png",
            requires:["MEM-0002"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0005",
            chapterId:"CH-000",
            order:5,
            rarity:"RARE",
            drawWeight:30,
            type:"CHECKUP",
            title:"우리 가족이 된 첫 순간",
            date:"2025-06-21",
            description:"처음으로 화면 속 작은 생명의 모습을 확인한 특별한 기록",
            photo:"card0005.png",
            requires:["MEM-0004"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0006",
            chapterId:"CH-000",
            order:6,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"작은 생명의 모습",
            date:"2025-06-21",
            description:"초음파 화면 속에서 조금씩 자라고 있는 아기의 모습을 만난 날",
            photo:"card0006.png",
            requires:["MEM-0005"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0007",
            chapterId:"CH-000",
            order:7,
            rarity:"LEGEND",
            drawWeight:3,
            type:"FIRST",
            title:"처음 들은 심장 소리",
            date:"2025-06-21",
            description:"작지만 분명하게 들려온 생명의 신호를 처음 만난 순간",
            photo:"card0007.png",
            requires:["MEM-0006"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0008",
            chapterId:"CH-000",
            order:8,
            rarity:"RARE",
            drawWeight:30,
            type:"ULTRASOUND",
            title:"첫 초음파 사진",
            date:"2025-06-21",
            description:"우리 아기의 첫 모습을 사진으로 남긴 소중한 기억",
            photo:"card0008.png",
            requires:["MEM-0007"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0009",
            chapterId:"CH-000",
            order:9,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"손과 발을 확인하다",
            date:"2025-07-19",
            description:"작은 손과 발이 자라고 있음을 확인하며 한 걸음 더 가까워진 날",
            photo:"card0009.png",
            requires:["MEM-0008"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0010",
            chapterId:"CH-000",
            order:10,
            rarity:"LEGEND",
            drawWeight:3,
            type:"ULTRASOUND",
            title:"입체초음파 첫 만남",
            date:"2025-11-08",
            description:"평면 화면을 넘어 아기의 모습을 조금 더 선명하게 만난 특별한 순간",
            photo:"card0010.png",
            requires:["MEM-0009"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0011",
            chapterId:"CH-000",
            order:11,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"산전 기형아 검사",
            date:"2025-08-20",
            description:"아기의 건강한 성장을 확인하기 위해 중요한 검사를 진행한 날",
            photo:"card0011.png",
            requires:["MEM-0010"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0012",
            chapterId:"CH-000",
            order:12,
            rarity:"EPIC",
            drawWeight:10,
            type:"ULTRASOUND",
            title:"두 번째 성장 확인",
            date:"2025-08-16",
            description:"조금씩 자라나는 아기의 모습을 다시 만난 소중한 초음파 기록",
            photo:"card0012.png",
            requires:["MEM-0011"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0013",
            chapterId:"CH-000",
            order:13,
            rarity:"RARE",
            drawWeight:30,
            type:"FIRST",
            title:"처음 느낀 태동",
            date:"2025-08-25",
            description:"엄마와 아기가 처음으로 서로의 존재를 느낀 특별한 순간",
            photo:"card0013.png",
            requires:["MEM-0012"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0014",
            chapterId:"CH-000",
            order:14,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"성별 확인",
            date:"2025-08-25",
            description:"오랫동안 기다려온 아기의 이야기를 조금 더 알게 된 날",
            photo:"card0014.png",
            requires:["MEM-0013"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0015",
            chapterId:"CH-000",
            order:15,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"배가 조금씩 커지는 시간",
            date:"2025-09-20",
            description:"아기가 자라는 만큼 엄마의 하루도 조금씩 변화하기 시작한 시간",
            photo:"card0015.png",
            requires:["MEM-0014"],
            maxLevel:20,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0016",
            chapterId:"CH-000",
            order:16,
            rarity:"RARE",
            drawWeight:30,
            type:"PHOTO",
            title:"아기와 함께한 첫 사진",
            date:"2025-10-05",
            description:"엄마와 아기가 함께 남긴 특별한 가족의 기록",
            photo:"card0016.png",
            requires:["MEM-0015"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0017",
            chapterId:"CH-000",
            order:17,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"정밀 초음파 검사",
            date:"2025-10-11",
            description:"아기의 성장 모습을 자세히 확인하며 건강을 확인한 날",
            photo:"card0017.png",
            requires:["MEM-0016"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0018",
            chapterId:"CH-000",
            order:18,
            rarity:"RARE",
            drawWeight:30,
            type:"FAMILY",
            title:"가족에게 전한 소식",
            date:"2025-10-15",
            description:"새로운 가족을 기다리는 마음을 함께 나눈 따뜻한 순간",
            photo:"card0018.png",
            requires:["MEM-0017"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0019",
            chapterId:"CH-000",
            order:19,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"아기 이름 고민하기",
            date:"2025-11-01",
            description:"우리 아기에게 어울리는 이름을 고민하기 시작한 시간",
            photo:"card0019.png",
            requires:["MEM-0018"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0020",
            chapterId:"CH-000",
            order:20,
            rarity:"EPIC",
            drawWeight:10,
            type:"CHECKUP",
            title:"임당 검사",
            date:"2025-11-10",
            description:"엄마와 아기의 건강을 위해 꼼꼼하게 확인한 중요한 검사",
            photo:"card0020.png",
            requires:["MEM-0019"],
            maxLevel:30,
            skill:"DRAW_COOLDOWN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0021",
            chapterId:"CH-000",
            order:21,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"아기 용품 준비 시작",
            date:"2025-11-25",
            description:"아기를 만날 준비를 시작하며 작은 설렘을 채워간 시간",
            photo:"card0021.png",
            requires:["MEM-0020"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0022",
            chapterId:"CH-000",
            order:22,
            rarity:"EPIC",
            drawWeight:10,
            type:"PHOTO",
            title:"만삭 사진 촬영",
            date:"2025-12-05",
            description:"아기를 기다리는 지금의 모습을 오래 기억하기 위해 남긴 특별한 기록",
            photo:"card0022.png",
            requires:["MEM-0021"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:30,
            skillValueWeight:1
        },
        {
            id:"MEM-0023",
            chapterId:"CH-000",
            order:23,
            rarity:"RARE",
            drawWeight:30,
            type:"ULTRASOUND",
            title:"출산 전 마지막 초음파",
            date:"2026-01-23",
            description:"곧 만나게 될 아기의 모습을 마지막으로 확인한 소중한 순간",
            photo:"card0023.png",
            requires:["MEM-0022"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0024",
            chapterId:"CH-000",
            order:24,
            rarity:"EPIC",
            drawWeight:10,
            type:"MILESTONE",
            title:"출산 준비 완료",
            date:"2026-02-01",
            description:"아기를 맞이하기 위한 모든 준비를 마친 설레는 순간",
            photo:"card0024.png",
            requires:["MEM-0023"],
            maxLevel:30,
            skill:"DRAW_COUNT",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0025",
            chapterId:"CH-000",
            order:25,
            rarity:"LEGEND",
            drawWeight:1,
            type:"SPECIAL",
            title:"마지막 기다림",
            date:"2026-02-02",
            description:"새로운 가족을 만나기 바로 전날, 가장 설레는 기다림의 순간",
            photo:"card0025.png",
            requires:["MEM-0024"],
            maxLevel:40,
            skill:"UNLOCK_CHAPTER",
            skillValue:1,
            skillValueWeight:0
        },
        {
            id:"MEM-0026",
            chapterId:"CH-000",
            order:26,
            rarity:"RARE",
            drawWeight:30,
            type:"PREPARATION",
            title:"엄마가 되는 첫 번째 준비",
            date:"2025-06-18",
            description:"아기를 위한 첫 번째 준비를 시작하며 새로운 역할을 받아들인 날",
            photo:"card0026.png",
            requires:["MEM-0002"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0027",
            chapterId:"CH-000",
            order:27,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"처음 찾아간 보건소",
            date:"2025-06-26",
            description:"엄마와 아기를 위한 지원을 알아보고 준비를 시작한 날",
            photo:"card0027.png",
            requires:["MEM-0004"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0028",
            chapterId:"CH-000",
            order:28,
            rarity:"NORMAL",
            drawWeight:100,
            type:"PREPARATION",
            title:"아기를 위한 작은 준비",
            date:"2025-06-26",
            description:"건강한 만남을 위해 매일 이어갈 준비를 시작한 순간",
            photo:"card0028.png",
            requires:["MEM-0027"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0029",
            chapterId:"CH-000",
            order:29,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"작은 행복이 된 간식",
            date:"2025-07-03",
            description:"임신 중 만난 평범하지만 오래 기억될 작은 순간",
            photo:"card0029.png",
            requires:["MEM-0028"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:2,
            skillValueWeight:1
        },
        {
            id:"MEM-0030",
            chapterId:"CH-000",
            order:30,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마를 위한 건강 습관",
            date:"2025-07-12",
            description:"아기를 생각하는 마음으로 하루를 채워간 시간",
            photo:"card0030.png",
            requires:["MEM-0029"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0031",
            chapterId:"CH-000",
            order:31,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"미래를 위한 약속",
            date:"2025-07-18",
            description:"아기의 미래를 생각하며 처음 준비한 보호의 기록",
            photo:"card0031.png",
            requires:["MEM-0007","MEM-0026"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0032",
            chapterId:"CH-000",
            order:32,
            rarity:"RARE",
            drawWeight:30,
            type:"SHOPPING",
            title:"작은 옷을 처음 준비한 날",
            date:"2025-07-20",
            description:"아주 작은 옷을 바라보며 만남을 상상했던 순간",
            photo:"card0032.png",
            requires:["MEM-0007","MEM-0031"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0033",
            chapterId:"CH-000",
            order:33,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마라는 이름의 시작",
            date:"2025-07-25",
            description:"새로운 가족을 기다리는 마음을 담은 작은 기록",
            photo:"card0033.png",
            requires:["MEM-0032"],
            maxLevel:20,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0034",
            chapterId:"CH-000",
            order:34,
            rarity:"NORMAL",
            drawWeight:100,
            type:"PREPARATION",
            title:"매일 이어지는 사랑",
            date:"2025-08-02",
            description:"아기의 건강을 위해 꾸준히 준비한 시간",
            photo:"card0034.png",
            requires:["MEM-0033"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0035",
            chapterId:"CH-000",
            order:35,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"다가오는 만남을 위한 준비",
            date:"2025-08-08",
            description:"앞으로 남을 특별한 순간을 준비하기 시작한 날",
            photo:"card0035.png",
            requires:["MEM-0010","MEM-0034"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0036",
            chapterId:"CH-000",
            order:36,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"아무도 모르는 작은 기록",
            date:"2025-06-26",
            description:"사진으로 남기지 못했지만 마음속에 남아있는 특별한 순간",
            photo:"card0036.png",
            requires:["MEM-0002","MEM-0027","MEM-0028","MEM-0031"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        },
        {
            id:"MEM-0037",
            chapterId:"CH-000",
            order:37,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"아빠의 첫 번째 준비",
            date:"2025-07-20",
            description:"아기를 기다리는 마음으로 준비한 작은 선물",
            photo:"card0037.png",
            requires:["MEM-0007","MEM-0031","MEM-0032"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0038",
            chapterId:"CH-000",
            order:38,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"우리 가족의 공간",
            date:"2025-08-21",
            description:"아기를 맞이할 준비를 하며 새로운 공간을 만들어가기 시작한 날",
            photo:"card0038.png",
            requires:["MEM-0035","MEM-0034"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0039",
            chapterId:"CH-000",
            order:39,
            rarity:"RARE",
            drawWeight:30,
            type:"BODY_CHANGE",
            title:"엄마에게 남은 작은 흔적",
            date:"2025-08-31",
            description:"아기가 자라고 있다는 것을 느끼게 해준 특별한 변화",
            photo:"card0039.png",
            requires:["MEM-0013","MEM-0034"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:5,
            skillValueWeight:1
        },
        {
            id:"MEM-0040",
            chapterId:"CH-000",
            order:40,
            rarity:"EPIC",
            drawWeight:10,
            type:"MILESTONE",
            title:"두 사람이 세 사람이 되는 의미",
            date:"2025-08-31",
            description:"가족이라는 의미를 다시 생각하게 된 특별한 하루",
            photo:"card0040.png",
            requires:["MEM-0001","MEM-0031"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0041",
            chapterId:"CH-000",
            order:41,
            rarity:"LEGEND",
            drawWeight:3,
            type:"TRAVEL",
            title:"마지막 둘만의 여행",
            date:"2025-09-04",
            description:"아기를 만나기 전 두 사람이 함께 남긴 마지막 특별한 여행",
            photo:"card0041.png",
            requires:["MEM-0013","MEM-0038","MEM-0040"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:30,
            skillValueWeight:1
        },
        {
            id:"MEM-0042",
            chapterId:"CH-000",
            order:42,
            rarity:"RARE",
            drawWeight:30,
            type:"FAMILY",
            title:"함께 기다리는 가족",
            date:"2025-09-13",
            description:"새로운 가족을 기다리는 마음을 함께 나눈 따뜻한 시간",
            photo:"card0042.png",
            requires:["MEM-0041"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0043",
            chapterId:"CH-000",
            order:43,
            rarity:"EPIC",
            drawWeight:10,
            type:"PREPARATION",
            title:"아기를 위한 첫 번째 공간",
            date:"2025-09-17",
            description:"작은 물건 하나하나에 사랑을 담아 준비하기 시작한 날",
            photo:"card0043.png",
            requires:["MEM-0038","MEM-0032"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:15,
            skillValueWeight:1
        },
        {
            id:"MEM-0044",
            chapterId:"CH-000",
            order:44,
            rarity:"NORMAL",
            drawWeight:100,
            type:"DAILY",
            title:"엄마를 위한 작은 휴식",
            date:"2025-10-01",
            description:"아기를 기다리는 엄마를 위해 준비한 작은 선물",
            photo:"card0044.png",
            requires:["MEM-0038"],
            maxLevel:20,
            skill:"POINT_GAIN",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0045",
            chapterId:"CH-000",
            order:45,
            rarity:"LEGEND",
            drawWeight:3,
            type:"MILESTONE",
            title:"함께한 100일",
            date:"2025-10-25",
            description:"아기를 기다린 시간도 하나의 추억이 된 특별한 날",
            photo:"card0045.png",
            requires:["MEM-0001","MEM-0041"],
            maxLevel:40,
            skill:"DRAW_COUNT",
            skillValue:3,
            skillValueWeight:1
        },
        {
            id:"MEM-0046",
            chapterId:"CH-000",
            order:46,
            rarity:"RARE",
            drawWeight:30,
            type:"MEMORY",
            title:"기억을 담을 공간",
            date:"2025-10-27",
            description:"소중한 순간들을 모아 하나의 이야기로 만들 준비를 시작한 날",
            photo:"card0046.png",
            requires:["MEM-0022","MEM-0045"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0047",
            chapterId:"CH-000",
            order:47,
            rarity:"RARE",
            drawWeight:30,
            type:"TRAVEL",
            title:"함께 걸은 가을",
            date:"2025-11-01",
            description:"아기를 기다리며 남긴 따뜻한 계절의 기록",
            photo:"card0047.png",
            requires:["MEM-0041"],
            maxLevel:25,
            skill:"POINT_GAIN",
            skillValue:10,
            skillValueWeight:1
        },
        {
            id:"MEM-0048",
            chapterId:"CH-000",
            order:48,
            rarity:"EPIC",
            drawWeight:10,
            type:"PHOTO",
            title:"마지막 순간을 위한 준비",
            date:"2025-11-05",
            description:"만남을 앞두고 특별한 기록을 남기기 위해 준비한 시간",
            photo:"card0048.png",
            requires:["MEM-0022","MEM-0046"],
            maxLevel:30,
            skill:"POINT_GAIN",
            skillValue:20,
            skillValueWeight:1
        },
        {
            id:"MEM-0049",
            chapterId:"CH-000",
            order:49,
            rarity:"RARE",
            drawWeight:30,
            type:"SPECIAL",
            title:"세 사람의 이름",
            date:"2025-12-02",
            description:"가족이 될 순간을 기다리며 준비한 작은 장식",
            photo:"card0049.png",
            requires:["MEM-0048"],
            maxLevel:25,
            skill:"DRAW_COUNT",
            skillValue:1,
            skillValueWeight:1
        },
        {
            id:"MEM-0050",
            chapterId:"CH-000",
            order:50,
            rarity:"SECRET",
            drawWeight:1,
            type:"HIDDEN",
            title:"겨울의 작은 행복",
            date:"2025-12-23",
            description:"특별한 사건은 아니지만 오래 기억될 평범하고 따뜻한 하루",
            photo:"card0050.png",
            requires:["MEM-0045","MEM-0047","MEM-0049"],
            maxLevel:40,
            skill:"POINT_GAIN",
            skillValue:50,
            skillValueWeight:1
        }
    ]
};